dist: focal
addons:
  apt:
    packages:
      - software-properties-common
      - wget
      - make
      - g++
      - cmake
      - zlib1g
      - zlib1g-dev
      - libsnappy-dev
      - libzstd-dev
      - libbz2-dev
      - liblz4-dev
      - libgflags-dev
      - liburing-dev
      - git
      - vim
      - openssh-client
      - openssh-server
      - openssh-sftp-server
      - python3
      - python3-pip
      - net-tools
      - iputils-ping
      - iproute2
      - rsync
      - gdb

language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
before_install:
  - ./script/build_third_party.sh
script:
  - ./script/build.sh
after_success:
  - ./script/build_success.sh
notifications:
  email: false